//! Workspace automation for the slang Rust bindings.
//!
//! `cargo xtask codegen` regenerates every committed `generated/*.rs` file from
//! the vendored JSON models under `rust/model/`, which are themselves produced
//! by `scripts/syntax_gen.py --emit-model` and `scripts/diagnostic_gen.py
//! --emit-model`. `cargo xtask codegen --check` regenerates into memory and
//! fails if any committed file is stale.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::Deserialize;

mod wasm_bridge;

const SLANG_VERSION: &str = "11.0";

#[derive(Deserialize)]
struct SyntaxModel {
    #[serde(rename = "modelHash")]
    model_hash: String,
    #[serde(rename = "syntaxKinds")]
    syntax_kinds: Vec<String>,
    #[serde(rename = "kindToStruct")]
    kind_to_struct: std::collections::BTreeMap<String, String>,
    #[serde(rename = "tokenKinds")]
    token_kinds: Vec<String>,
    #[serde(rename = "triviaKinds")]
    trivia_kinds: Vec<String>,
    structs: Vec<SyntaxStruct>,
}

#[derive(Deserialize)]
struct SyntaxStruct {
    name: String,
    base: String,
    #[serde(rename = "final")]
    is_final: bool,
    #[serde(default)]
    kinds: Vec<String>,
    #[serde(default)]
    members: Vec<SyntaxMember>,
}

#[derive(Deserialize)]
struct SyntaxMember {
    name: String,
    form: String,
    #[serde(rename = "type")]
    node_type: Option<String>,
    #[serde(default)]
    optional: bool,
    element: Option<String>,
}

#[derive(Deserialize)]
struct DiagModel {
    #[serde(rename = "modelHash")]
    model_hash: String,
    subsystems: Vec<DiagSubsystem>,
    groups: Vec<DiagGroup>,
}

#[derive(Deserialize)]
struct DiagSubsystem {
    name: String,
    diagnostics: Vec<DiagEntry>,
}

#[derive(Deserialize)]
struct DiagEntry {
    name: String,
    index: u16,
    severity: String,
    message: String,
    option: Option<String>,
}

#[derive(Deserialize)]
struct DiagGroup {
    name: String,
    options: Vec<String>,
}

#[derive(Deserialize)]
struct AstKindsModel {
    #[serde(rename = "modelHash")]
    model_hash: String,
    enums: std::collections::BTreeMap<String, AstEnum>,
}

#[derive(Deserialize)]
struct AstEnum {
    header: String,
    values: Vec<String>,
}

/// The `DiagSubsystem` enumerators in the exact order declared by the X-macro
/// in `include/slang/diagnostics/Diagnostics.h`. That enum is hand-written in
/// C++, so this list must be kept in sync by hand; a test in `sv-lang-kinds`
/// cross-checks it against the model's subsystem set.
const DIAG_SUBSYSTEMS: &[&str] = &[
    "General",
    "Lexer",
    "Numeric",
    "Preprocessor",
    "Parser",
    "Declarations",
    "Expressions",
    "Statements",
    "Types",
    "Lookup",
    "SysFuncs",
    "ConstEval",
    "Compilation",
    "Analysis",
    "Meta",
    "Driver",
    "Tidy",
    "Netlist",
];

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
];

fn ident(name: &str) -> String {
    if RUST_KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

struct Generated {
    path: PathBuf,
    contents: String,
}

fn header(source: &str) -> String {
    format!(
        "// @generated by `cargo xtask codegen` from {source}. Do not edit by hand;\n\
         // edit the model inputs in slang's scripts/ directory and regenerate.\n\n"
    )
}

/// Emits a plain `#[repr(uN)]` kind enum with dense ordinals starting at zero.
fn emit_kind_enum(out: &mut String, enum_name: &str, repr: &str, doc: &str, names: &[String]) {
    let _ = writeln!(out, "/// {doc}");
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// Discriminants match slang's C++ `{enum_name}` enum exactly, so values can be\n\
         /// exchanged with the native library as raw integers via [`Self::from_raw`]."
    );
    let _ = writeln!(out, "#[repr({repr})]");
    let _ = writeln!(out, "#[non_exhaustive]");
    let _ = writeln!(
        out,
        "#[allow(missing_docs)] // variant names are slang's own and self-describing"
    );
    let _ = writeln!(
        out,
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]"
    );
    let _ = writeln!(out, "pub enum {enum_name} {{");
    for (i, name) in names.iter().enumerate() {
        let _ = writeln!(out, "    {} = {i},", ident(name));
    }
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(out, "impl {enum_name} {{");
    let _ = writeln!(out, "    /// The number of variants.");
    let _ = writeln!(out, "    pub const COUNT: {repr} = {};", names.len());
    let _ = writeln!(out, "\n    /// Every variant, in discriminant order.");
    let _ = writeln!(out, "    pub const ALL: &'static [{enum_name}] = &[");
    for name in names {
        let _ = writeln!(out, "        {enum_name}::{},", ident(name));
    }
    let _ = writeln!(out, "    ];\n");
    let _ = writeln!(out, "    const NAMES: &'static [&'static str] = &[");
    for name in names {
        let _ = writeln!(out, "        {name:?},");
    }
    let _ = writeln!(out, "    ];\n");
    let _ = writeln!(
        out,
        "    /// Converts a raw discriminant from the native library, returning `None`\n\
         \x20   /// for values outside the known range.\n\
         \x20   #[inline]\n\
         \x20   pub const fn from_raw(raw: {repr}) -> Option<Self> {{\n\
         \x20       if (raw as usize) < Self::ALL.len() {{\n\
         \x20           Some(Self::ALL[raw as usize])\n\
         \x20       }} else {{\n\
         \x20           None\n\
         \x20       }}\n\
         \x20   }}\n\n\
         \x20   /// The raw discriminant.\n\
         \x20   #[inline]\n\
         \x20   pub const fn as_raw(self) -> {repr} {{\n\
         \x20       self as {repr}\n\
         \x20   }}\n\n\
         \x20   /// The enumerator's name as spelled in slang.\n\
         \x20   #[inline]\n\
         \x20   pub const fn name(self) -> &'static str {{\n\
         \x20       Self::NAMES[self as usize]\n\
         \x20   }}\n\
         }}\n"
    );
    let _ = writeln!(
        out,
        "impl core::fmt::Display for {enum_name} {{\n\
         \x20   fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n\
         \x20       f.write_str(self.name())\n\
         \x20   }}\n\
         }}\n"
    );
}

fn gen_syntax_kind(model: &SyntaxModel) -> String {
    let mut out = header("rust/model/syntax-model-*.json");
    emit_kind_enum(
        &mut out,
        "SyntaxKind",
        "u16",
        "The kind of a syntax node in the concrete syntax tree.",
        &model.syntax_kinds,
    );

    // Struct ids: every generated C++ syntax struct, in model order.
    let _ = writeln!(
        out,
        "/// Identifies one of the generated C++ syntax node structs.\n\
         ///\n\
         /// Several [`SyntaxKind`]s can map to the same struct (for example every\n\
         /// binary operator kind is a `BinaryExpressionSyntax`); see\n\
         /// [`SyntaxKind::syntax_struct`]."
    );
    let _ = writeln!(out, "#[repr(u16)]");
    let _ = writeln!(out, "#[non_exhaustive]");
    let _ = writeln!(
        out,
        "#[allow(missing_docs)] // variant names are slang's own and self-describing"
    );
    let _ = writeln!(
        out,
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]"
    );
    let _ = writeln!(out, "pub enum SyntaxStruct {{");
    for (i, s) in model.structs.iter().enumerate() {
        let _ = writeln!(out, "    {} = {i},", ident(&s.name));
    }
    let _ = writeln!(out, "}}\n");
    let _ = writeln!(out, "impl SyntaxStruct {{");
    let _ = writeln!(out, "    /// The number of variants.");
    let _ = writeln!(out, "    pub const COUNT: u16 = {};", model.structs.len());
    let _ = writeln!(out, "\n    const NAMES: &'static [&'static str] = &[");
    for s in &model.structs {
        let _ = writeln!(out, "        {:?},", s.name);
    }
    let _ = writeln!(out, "    ];\n");
    let _ = writeln!(out, "    const IS_FINAL: &'static [bool] = &[");
    for s in &model.structs {
        let _ = writeln!(out, "        {},", s.is_final);
    }
    let _ = writeln!(out, "    ];\n");
    let _ = writeln!(
        out,
        "    /// The struct's C++ name, e.g. `\"BinaryExpressionSyntax\"`.\n\
         \x20   #[inline]\n\
         \x20   pub const fn name(self) -> &'static str {{\n\
         \x20       Self::NAMES[self as usize]\n\
         \x20   }}\n\n\
         \x20   /// Whether the struct is concrete (`final`) rather than an abstract base.\n\
         \x20   #[inline]\n\
         \x20   pub const fn is_final(self) -> bool {{\n\
         \x20       Self::IS_FINAL[self as usize]\n\
         \x20   }}\n\
         }}\n"
    );

    // Kind -> struct table.
    let struct_index: std::collections::HashMap<&str, usize> = model
        .structs
        .iter()
        .enumerate()
        .map(|(i, s)| (s.name.as_str(), i))
        .collect();
    let _ = writeln!(out, "impl SyntaxKind {{");
    let _ = writeln!(
        out,
        "    const STRUCTS: &'static [Option<SyntaxStruct>] = &["
    );
    for kind in &model.syntax_kinds {
        match model.kind_to_struct.get(kind) {
            Some(s) => {
                let _ = writeln!(
                    out,
                    "        Some(SyntaxStruct::{}),",
                    ident(&model.structs[struct_index[s.as_str()]].name)
                );
            }
            None => {
                let _ = writeln!(out, "        None,");
            }
        }
    }
    let _ = writeln!(out, "    ];\n");
    let _ = writeln!(
        out,
        "    /// The generated C++ struct that nodes of this kind are instances of.\n\
         \x20   /// `None` only for [`SyntaxKind::Unknown`].\n\
         \x20   #[inline]\n\
         \x20   pub const fn syntax_struct(self) -> Option<SyntaxStruct> {{\n\
         \x20       Self::STRUCTS[self as usize]\n\
         \x20   }}\n\
         }}\n"
    );

    let _ = writeln!(
        out,
        "/// SHA-256 of the canonical syntax model these tables were generated from.\n\
         pub const SYNTAX_MODEL_HASH: &str = {:?};\n\n\
         /// The slang version the syntax model was generated from.\n\
         pub const SLANG_VERSION: &str = {SLANG_VERSION:?};",
        model.model_hash
    );
    out
}

fn gen_token_kind(model: &SyntaxModel) -> String {
    let mut out = header("rust/model/syntax-model-*.json");
    emit_kind_enum(
        &mut out,
        "TokenKind",
        "u16",
        "The kind of a lexical token.",
        &model.token_kinds,
    );
    emit_kind_enum(
        &mut out,
        "TriviaKind",
        "u8",
        "The kind of a piece of trivia (whitespace, comments, directives) attached to a token.",
        &model.trivia_kinds,
    );
    out
}

fn gen_diag_code(model: &DiagModel) -> String {
    let mut out = header("rust/model/diagnostics-model-*.json");
    let names: Vec<String> = DIAG_SUBSYSTEMS.iter().map(|s| s.to_string()).collect();
    emit_kind_enum(
        &mut out,
        "DiagSubsystem",
        "u16",
        "The subsystem a diagnostic belongs to.",
        &names,
    );

    let _ = writeln!(
        out,
        "/// The default severity of a diagnostic.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\n\
         pub enum DiagSeverity {{\n\
         \x20   /// The diagnostic is suppressed entirely.\n\
         \x20   Ignored,\n\
         \x20   /// Supplementary information attached to another diagnostic.\n\
         \x20   Note,\n\
         \x20   /// A warning; does not fail compilation.\n\
         \x20   Warning,\n\
         \x20   /// An error; compilation fails.\n\
         \x20   Error,\n\
         \x20   /// A fatal error; compilation stops immediately.\n\
         \x20   Fatal,\n\
         }}\n"
    );

    let _ = writeln!(
        out,
        "/// Identifies one diagnostic: a subsystem plus an index within it.\n\
         ///\n\
         /// The pair matches slang's C++ `DiagCode` exactly. Named constants for every\n\
         /// diagnostic live in the [`diag`] module.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\n\
         pub struct DiagCode {{\n\
         \x20   /// The subsystem that owns this diagnostic.\n\
         \x20   pub subsystem: DiagSubsystem,\n\
         \x20   /// The diagnostic's index within its subsystem.\n\
         \x20   pub code: u16,\n\
         }}\n"
    );

    // Per-subsystem tables, indexed by code.
    let by_name: std::collections::HashMap<&str, &DiagSubsystem> = model
        .subsystems
        .iter()
        .map(|s| (s.name.as_str(), s))
        .collect();

    let _ = writeln!(out, "impl DiagCode {{");
    let _ = writeln!(
        out,
        "    /// Constructs a code from a subsystem and an index within it. Prefer the\n\
         \x20   /// named constants in [`diag`]; this is for values received from the\n\
         \x20   /// native library.\n\
         \x20   #[inline]\n\
         \x20   pub const fn new(subsystem: DiagSubsystem, code: u16) -> Self {{\n\
         \x20       Self {{ subsystem, code }}\n\
         \x20   }}\n\n\
         \x20   /// Packs the code into a single `u32` (`subsystem << 16 | code`), the\n\
         \x20   /// representation used across the C ABI.\n\
         \x20   #[inline]\n\
         \x20   pub const fn as_raw(self) -> u32 {{\n\
         \x20       ((self.subsystem as u32) << 16) | self.code as u32\n\
         \x20   }}\n\n\
         \x20   /// Unpacks a `u32` produced by [`Self::as_raw`]. Returns `None` if the\n\
         \x20   /// subsystem or code is out of the known range.\n\
         \x20   pub const fn from_raw(raw: u32) -> Option<Self> {{\n\
         \x20       let Some(subsystem) = DiagSubsystem::from_raw((raw >> 16) as u16) else {{\n\
         \x20           return None;\n\
         \x20       }};\n\
         \x20       let code = (raw & 0xFFFF) as u16;\n\
         \x20       if (code as usize) < Self::table(subsystem).len() {{\n\
         \x20           Some(Self {{ subsystem, code }})\n\
         \x20       }} else {{\n\
         \x20           None\n\
         \x20       }}\n\
         \x20   }}\n\n\
         \x20   /// The diagnostic's name as declared in slang, e.g. `\"UnknownModule\"`.\n\
         \x20   #[inline]\n\
         \x20   pub const fn name(self) -> &'static str {{\n\
         \x20       Self::table(self.subsystem)[self.code as usize].0\n\
         \x20   }}\n\n\
         \x20   /// The diagnostic's default severity.\n\
         \x20   #[inline]\n\
         \x20   pub const fn default_severity(self) -> DiagSeverity {{\n\
         \x20       Self::table(self.subsystem)[self.code as usize].1\n\
         \x20   }}\n\n\
         \x20   /// The warning option name (without the `-W` prefix), if this diagnostic\n\
         \x20   /// is a warning that can be controlled from the command line.\n\
         \x20   #[inline]\n\
         \x20   pub const fn option_name(self) -> Option<&'static str> {{\n\
         \x20       Self::table(self.subsystem)[self.code as usize].2\n\
         \x20   }}\n\n\
         \x20   /// The diagnostic's message format string.\n\
         \x20   #[inline]\n\
         \x20   pub const fn message_format(self) -> &'static str {{\n\
         \x20       Self::table(self.subsystem)[self.code as usize].3\n\
         \x20   }}\n\n\
         \x20   const fn table(subsystem: DiagSubsystem) -> &'static [DiagInfo] {{\n\
         \x20       match subsystem {{"
    );
    for sub in DIAG_SUBSYSTEMS {
        let _ = writeln!(
            out,
            "            DiagSubsystem::{} => {}_TABLE,",
            ident(sub),
            sub.to_uppercase()
        );
    }
    let _ = writeln!(out, "        }}\n    }}\n}}\n");

    let _ = writeln!(
        out,
        "type DiagInfo = (&'static str, DiagSeverity, Option<&'static str>, &'static str);\n"
    );
    for sub in DIAG_SUBSYSTEMS {
        let _ = writeln!(out, "const {}_TABLE: &[DiagInfo] = &[", sub.to_uppercase());
        if let Some(s) = by_name.get(sub) {
            for (i, d) in s.diagnostics.iter().enumerate() {
                assert_eq!(i as u16, d.index, "non-dense diag index in {}", sub);
                let opt = match &d.option {
                    Some(o) => format!("Some({o:?})"),
                    None => "None".to_string(),
                };
                let _ = writeln!(
                    out,
                    "    ({:?}, DiagSeverity::{}, {opt}, {:?}),",
                    d.name, d.severity, d.message
                );
            }
        }
        let _ = writeln!(out, "];\n");
    }

    // Named constants.
    let _ = writeln!(
        out,
        "/// Named constants for every diagnostic slang can emit.\n\
         #[allow(non_upper_case_globals, missing_docs)] // names match slang's `diag::` namespace\n\
         pub mod diag {{\n\
         \x20   use super::{{DiagCode, DiagSubsystem}};\n"
    );
    for sub in &model.subsystems {
        for d in &sub.diagnostics {
            let _ = writeln!(
                out,
                "    pub const {}: DiagCode = DiagCode::new(DiagSubsystem::{}, {});",
                ident(&d.name),
                ident(&sub.name),
                d.index
            );
        }
    }
    let _ = writeln!(out, "}}\n");

    // Groups.
    let _ = writeln!(
        out,
        "/// A named group of warning options, e.g. `default` or `extra`.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n\
         pub struct DiagGroup {{\n\
         \x20   /// The group name as used with `-W`.\n\
         \x20   pub name: &'static str,\n\
         \x20   /// The warning option names the group enables.\n\
         \x20   pub options: &'static [&'static str],\n\
         }}\n\n\
         /// Every warning group slang defines.\n\
         pub const DIAG_GROUPS: &[DiagGroup] = &["
    );
    for g in &model.groups {
        let _ = writeln!(out, "    DiagGroup {{ name: {:?}, options: &[", g.name);
        for o in &g.options {
            let _ = writeln!(out, "        {o:?},");
        }
        let _ = writeln!(out, "    ] }},");
    }
    let _ = writeln!(out, "];\n");

    let _ = writeln!(
        out,
        "/// SHA-256 of the canonical diagnostics model these tables were generated from.\n\
         pub const DIAGNOSTICS_MODEL_HASH: &str = {:?};",
        model.model_hash
    );
    out
}

fn gen_ast_kind(model: &AstKindsModel) -> String {
    let mut out = header("rust/model/ast-kinds-*.json");
    for (name, e) in &model.enums {
        let noun = name.strip_suffix("Kind").unwrap_or(name);
        let doc = format!(
            "The kind of an elaborated `{noun}` AST node (from `{}`).",
            e.header
        );
        emit_kind_enum(&mut out, name, "u16", &doc, &e.values);
    }
    let _ = writeln!(
        out,
        "/// SHA-256 of the canonical AST-kinds model these tables were generated from.\n\
         pub const AST_KINDS_MODEL_HASH: &str = {:?};",
        model.model_hash
    );
    out
}

/// Formats generated source with `rustfmt` so that committed output is stable
/// under `cargo fmt --all` and `codegen --check` stays idempotent.
/// Converts slang's lowerCamelCase member names to snake_case.
fn snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// The Rust type a member of the given slang type maps to.
fn member_type(ty: &str) -> String {
    if ty == "SyntaxNode" {
        "Node<'t>".to_string()
    } else {
        format!("{ty}<'t>")
    }
}

/// Generates a syn-style `Visitor` trait: one `visit_<kind>` method per
/// concrete syntax node (defaulted to walk into children) plus a `visit`
/// dispatcher that routes a `Node` to the right method by its kind.
fn gen_visitor(model: &SyntaxModel) -> String {
    let mut finals: Vec<&SyntaxStruct> = model.structs.iter().filter(|s| s.is_final).collect();
    finals.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = header("scripts/syntax.txt (via rust/model/syntax-model-*.json)");
    out.push_str(
        "#![allow(clippy::too_many_lines)]\n\n\
         use sv_lang_kinds::SyntaxStruct;\n\n\
         use crate::syntax::nodes::*;\n\
         use crate::syntax::{AstNode, Node};\n\n\
         /// A visitor over a typed syntax tree, in the style of `syn::visit`.\n\
         ///\n\
         /// Implement the `visit_*` methods for the node kinds you care about;\n\
         /// each defaults to walking into the node's children. Call\n\
         /// [`visit`] with the tree root (or any [`Node`]) to drive it. To\n\
         /// descend after handling a node, call the matching `walk_*` function\n\
         /// (or the default method body); to prune, simply return.\n\
         #[allow(unused_variables)]\n\
         pub trait Visitor<'t>: Sized {\n",
    );
    for s in &finals {
        let snake = snake_case(&s.name);
        let _ = writeln!(
            out,
            "    /// Visits a [`{name}`]. Defaults to walking its children.\n    \
             fn visit_{snake}(&mut self, node: {name}<'t>) {{\n        walk_{snake}(self, node);\n    }}",
            name = s.name,
        );
    }
    out.push_str("}\n\n");

    for s in &finals {
        let snake = snake_case(&s.name);
        let _ = writeln!(
            out,
            "/// Walks the children of a [`{name}`], visiting each.\n\
             pub fn walk_{snake}<'t, V: Visitor<'t> + ?Sized>(v: &mut V, node: {name}<'t>) {{\n    \
             for child in node.syntax().children() {{\n        visit(v, child);\n    }}\n}}\n",
            name = s.name,
        );
    }

    out.push_str(
        "/// Dispatches a [`Node`] to the matching `visit_*` method of `v`\n\
         /// according to its syntax kind, then (through the default method)\n\
         /// walks its children.\n\
         pub fn visit<'t, V: Visitor<'t> + ?Sized>(v: &mut V, node: Node<'t>) {\n    \
         match node.syntax_struct() {\n",
    );
    for s in &finals {
        let snake = snake_case(&s.name);
        let _ = writeln!(
            out,
            "        Some(SyntaxStruct::{name}) => {{\n            \
             if let Some(n) = {name}::cast(node) {{\n                v.visit_{snake}(n);\n            }}\n        }}",
            name = s.name,
        );
    }
    out.push_str(
        "        _ => {\n            for child in node.children() {\n                visit(v, child);\n            }\n        }\n    }\n}\n",
    );
    out
}

/// Generates the typed syntax node structs and base-type enums for `sv-lang`,
/// sharded into several files to keep compile times reasonable.
fn gen_syntax_nodes(model: &SyntaxModel) -> Vec<(String, String)> {
    const SHARDS: usize = 8;

    // Direct derived structs of each abstract base, in model order.
    let mut derived: std::collections::BTreeMap<&str, Vec<&SyntaxStruct>> = Default::default();
    for s in &model.structs {
        derived.entry(s.base.as_str()).or_default().push(s);
    }
    // All final structs transitively under an abstract base.
    fn finals<'a>(
        name: &'a str,
        derived: &std::collections::BTreeMap<&'a str, Vec<&'a SyntaxStruct>>,
        out: &mut Vec<&'a str>,
    ) {
        if let Some(children) = derived.get(name) {
            for c in children {
                if c.is_final {
                    out.push(c.name.as_str());
                } else {
                    finals(&c.name, derived, out);
                }
            }
        }
    }

    let per_shard = model.structs.len().div_ceil(SHARDS);
    let mut files = Vec::new();
    for (shard, chunk) in model.structs.chunks(per_shard).enumerate() {
        let mut out = header("scripts/syntax.txt (via rust/model/syntax-model-*.json)");
        out.push_str(
            "#![allow(clippy::too_many_lines, unused_imports)]\n\n\
             use sv_lang_kinds::{SyntaxKind, SyntaxStruct};\n\n\
             use crate::syntax::nodes::*;\n\
             use crate::syntax::{AstNode, Node, SeparatedList, SyntaxList, Token, TokenList};\n\n",
        );

        for s in chunk {
            let name = &s.name;
            if s.is_final {
                let _ = writeln!(
                    out,
                    "/// Typed view of a [`Node`] whose struct is [`SyntaxStruct::{name}`].\n\
                     ///\n\
                     /// Kinds: {kinds}.\n\
                     #[derive(Clone, Copy, PartialEq, Eq, Hash)]\n\
                     pub struct {name}<'t> {{\n    node: Node<'t>,\n}}\n\n\
                     impl<'t> AstNode<'t> for {name}<'t> {{\n\
                     \x20   fn can_cast(kind: SyntaxKind) -> bool {{\n\
                     \x20       kind.syntax_struct() == Some(SyntaxStruct::{name})\n    }}\n\n\
                     \x20   fn cast(node: Node<'t>) -> Option<Self> {{\n\
                     \x20       Self::can_cast(node.kind()).then_some(Self {{ node }})\n    }}\n\n\
                     \x20   fn syntax(&self) -> Node<'t> {{\n        self.node\n    }}\n}}\n\n\
                     impl core::fmt::Debug for {name}<'_> {{\n\
                     \x20   fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n\
                     \x20       core::fmt::Debug::fmt(&self.node, f)\n    }}\n}}\n",
                    kinds = s.kinds.join(", "),
                );
                let _ = writeln!(out, "impl<'t> {name}<'t> {{");
                for (i, m) in s.members.iter().enumerate() {
                    let method = ident(&snake_case(&m.name));
                    let (ret, body) = match m.form.as_str() {
                        "token" => (
                            "Option<Token<'t>>".to_string(),
                            format!("self.node.member_token({i})"),
                        ),
                        "node" => {
                            let ty = member_type(m.node_type.as_deref().unwrap_or("SyntaxNode"));
                            if m.optional {
                                (
                                    format!("Option<{ty}>"),
                                    format!("self.node.member_node({i}).and_then(<{ty}>::cast)"),
                                )
                            } else {
                                (
                                    ty.clone(),
                                    format!(
                                        "self.node.member_node({i}).and_then(<{ty}>::cast)\n            \
                                         .expect(\"slang guarantees this member is present\")"
                                    ),
                                )
                            }
                        }
                        "list" => {
                            let ty = member_type(m.element.as_deref().unwrap_or("SyntaxNode"));
                            (
                                format!("SyntaxList<'t, {ty}>"),
                                format!("self.node.member_list({i})"),
                            )
                        }
                        "separated_list" => {
                            let ty = member_type(m.element.as_deref().unwrap_or("SyntaxNode"));
                            (
                                format!("SeparatedList<'t, {ty}>"),
                                format!("self.node.member_separated_list({i})"),
                            )
                        }
                        "tokenlist" => (
                            "TokenList<'t>".to_string(),
                            format!("self.node.member_token_list({i})"),
                        ),
                        other => panic!("unknown member form {other}"),
                    };
                    let _ = writeln!(
                        out,
                        "    /// Member `{orig}` (child {i}).\n    pub fn {method}(&self) -> {ret} {{\n        {body}\n    }}\n",
                        orig = m.name,
                    );
                }
                out.push_str("}\n\n");
            } else {
                let children = derived.get(name.as_str()).cloned().unwrap_or_default();
                let mut all_finals = Vec::new();
                finals(name, &derived, &mut all_finals);
                let _ = writeln!(
                    out,
                    "/// Any node deriving from slang's abstract `{name}`.\n\
                     #[derive(Clone, Copy, PartialEq, Eq, Hash)]\n\
                     pub enum {name}<'t> {{",
                );
                for c in &children {
                    let variant = c.name.trim_end_matches("Syntax");
                    let _ = writeln!(
                        out,
                        "    /// A [`{}`].\n    {variant}({}<'t>),",
                        c.name, c.name
                    );
                }
                out.push_str("}\n\n");
                let _ = writeln!(
                    out,
                    "impl<'t> AstNode<'t> for {name}<'t> {{\n\
                     \x20   fn can_cast(kind: SyntaxKind) -> bool {{\n\
                     \x20       matches!(\n            kind.syntax_struct(),\n            {alts}\n        )\n    }}\n\n\
                     \x20   fn cast(node: Node<'t>) -> Option<Self> {{",
                    alts = all_finals
                        .iter()
                        .map(|f| format!("Some(SyntaxStruct::{f})"))
                        .collect::<Vec<_>>()
                        .join("\n                | "),
                );
                for c in &children {
                    let variant = c.name.trim_end_matches("Syntax");
                    let _ = writeln!(
                        out,
                        "        if let Some(n) = <{}<'t>>::cast(node) {{\n            return Some(Self::{variant}(n));\n        }}",
                        c.name
                    );
                }
                out.push_str("        None\n    }\n\n    fn syntax(&self) -> Node<'t> {\n        match self {\n");
                for c in &children {
                    let variant = c.name.trim_end_matches("Syntax");
                    let _ = writeln!(out, "            Self::{variant}(n) => n.syntax(),");
                }
                out.push_str("        }\n    }\n}\n\n");
                let _ = writeln!(
                    out,
                    "impl core::fmt::Debug for {name}<'_> {{\n\
                     \x20   fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{\n\
                     \x20       core::fmt::Debug::fmt(&self.syntax(), f)\n    }}\n}}\n",
                );
                for c in &children {
                    let variant = c.name.trim_end_matches("Syntax");
                    let _ = writeln!(
                        out,
                        "impl<'t> From<{}<'t>> for {name}<'t> {{\n    fn from(n: {}<'t>) -> Self {{\n        Self::{variant}(n)\n    }}\n}}\n",
                        c.name, c.name
                    );
                }
            }
        }
        files.push((format!("nodes_{shard}.rs"), out));
    }
    files
}

fn rustfmt(source: &str) -> Result<String, String> {
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("running rustfmt (is the `rustfmt` component installed?): {e}"))?;
    child
        .stdin
        .take()
        .expect("piped stdin")
        .write_all(source.as_bytes())
        .map_err(|e| format!("feeding rustfmt: {e}"))?;
    let out = child
        .wait_with_output()
        .map_err(|e| format!("waiting for rustfmt: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "rustfmt rejected generated code:\n{}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    String::from_utf8(out.stdout).map_err(|e| format!("rustfmt output not UTF-8: {e}"))
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives directly under the workspace root")
        .to_path_buf()
}

/// Reads and parses one versioned model file (`<name>-<version>.json`) from the
/// model directory.
fn load_model<T: serde::de::DeserializeOwned>(model_dir: &Path, name: &str) -> Result<T, String> {
    let path = model_dir.join(format!("{name}-{SLANG_VERSION}.json"));
    let text = std::fs::read_to_string(&path).map_err(|e| format!("reading {name} model: {e}"))?;
    serde_json::from_str(&text).map_err(|e| format!("parsing {name} model: {e}"))
}

fn generate(root: &Path) -> Result<Vec<Generated>, String> {
    let model_dir = root.join("model");
    let syntax: SyntaxModel = load_model(&model_dir, "syntax-model")?;
    let diags: DiagModel = load_model(&model_dir, "diagnostics-model")?;
    let ast: AstKindsModel = load_model(&model_dir, "ast-kinds")?;

    let kinds = root.join("sv-lang-kinds/src/generated");
    let mut files = vec![
        Generated {
            path: kinds.join("syntax_kind.rs"),
            contents: rustfmt(&gen_syntax_kind(&syntax))?,
        },
        Generated {
            path: kinds.join("token_kind.rs"),
            contents: rustfmt(&gen_token_kind(&syntax))?,
        },
        Generated {
            path: kinds.join("diag_code.rs"),
            contents: rustfmt(&gen_diag_code(&diags))?,
        },
        Generated {
            path: kinds.join("ast_kind.rs"),
            contents: rustfmt(&gen_ast_kind(&ast))?,
        },
    ];
    let nodes = root.join("sv-lang/src/syntax/generated");
    for (name, contents) in gen_syntax_nodes(&syntax) {
        files.push(Generated {
            path: nodes.join(name),
            contents: rustfmt(&contents)?,
        });
    }
    files.push(Generated {
        path: nodes.join("visitor.rs"),
        contents: rustfmt(&gen_visitor(&syntax))?,
    });

    // The wasm marshalling bridge, generated from the sys extern block.
    let sys_src = std::fs::read_to_string(root.join("sv-lang-sys/src/lib.rs"))
        .map_err(|e| format!("reading sv-lang-sys lib.rs: {e}"))?;
    files.push(Generated {
        path: root.join("sv-lang-wasm/src/generated/bridge.rs"),
        contents: rustfmt(&wasm_bridge::gen_wasm_bridge(&sys_src))?,
    });

    Ok(files)
}

/// Copies a directory tree, skipping any path for which `skip` returns true.
fn copy_tree(from: &Path, to: &Path, skip: &dyn Fn(&Path) -> bool) -> Result<u64, String> {
    let mut count = 0;
    std::fs::create_dir_all(to).map_err(|e| format!("creating {}: {e}", to.display()))?;
    let mut entries: Vec<_> = std::fs::read_dir(from)
        .map_err(|e| format!("reading {}: {e}", from.display()))?
        .map(|e| e.map(|e| e.path()))
        .collect::<Result<_, _>>()
        .map_err(|e| format!("reading {}: {e}", from.display()))?;
    entries.sort();
    for path in entries {
        if skip(&path) {
            continue;
        }
        let dest = to.join(path.file_name().unwrap());
        if path.is_dir() {
            count += copy_tree(&path, &dest, skip)?;
        } else {
            std::fs::copy(&path, &dest)
                .map_err(|e| format!("copying {} to {}: {e}", path.display(), dest.display()))?;
            count += 1;
        }
    }
    Ok(count)
}

/// Populates `sv-lang-sys/vendor/` with everything the published crate needs
/// to build slang without CMake, Python or network access: the C++ sources,
/// headers and bundled externals, the generators' output, and the version.
fn vendor(root: &Path) -> Result<(), String> {
    let repo = root.parent().ok_or("workspace has no parent")?;
    let dest = root.join("sv-lang-sys/vendor");
    for sub in ["source", "include", "external", "generated"] {
        let dir = dest.join(sub);
        if dir.exists() {
            std::fs::remove_dir_all(&dir)
                .map_err(|e| format!("removing {}: {e}", dir.display()))?;
        }
    }

    let tests = repo.join("source/capi/tests");
    let n = copy_tree(&repo.join("source"), &dest.join("source"), &|p| p == tests)?
        + copy_tree(&repo.join("include"), &dest.join("include"), &|_| false)?
        + copy_tree(&repo.join("external"), &dest.join("external"), &|p| {
            p.file_name().is_some_and(|n| n == "CMakeLists.txt")
        })?;
    println!("copied {n} source files");

    let generated = dest.join("generated");
    std::fs::create_dir_all(&generated).map_err(|e| e.to_string())?;
    let python = std::env::var("PYTHON").unwrap_or_else(|_| "python3".to_string());
    let run = |args: &[&str]| -> Result<(), String> {
        let status = std::process::Command::new(&python)
            .args(args)
            .current_dir(repo)
            .status()
            .map_err(|e| format!("running {python}: {e}"))?;
        if status.success() {
            Ok(())
        } else {
            Err(format!("{python} {args:?} failed"))
        }
    };
    let gen_dir = generated.to_str().unwrap();
    run(&[
        "scripts/syntax_gen.py",
        "--dir",
        gen_dir,
        "--syntax",
        "scripts/syntax.txt",
    ])?;
    run(&[
        "scripts/syntax_gen.py",
        "--dir",
        gen_dir,
        "--syntax",
        "scripts/syntax.txt",
        "--c-api",
        generated.join("SyntaxCApi.cpp").to_str().unwrap(),
    ])?;
    run(&[
        "scripts/diagnostic_gen.py",
        "--outDir",
        gen_dir,
        "--srcDir",
        "source",
        "--incDir",
        "include/slang",
        "--diagnostics",
        "scripts/diagnostics.txt",
    ])?;
    run(&[
        "scripts/diagnostic_gen.py",
        "--outDir",
        gen_dir,
        "--diagnostics",
        "scripts/diagnostics.txt",
        "--c-api",
        generated.join("DiagCApi.cpp").to_str().unwrap(),
    ])?;

    // The version, as build.rs derives it in-tree (see cmake/gitversion.cmake).
    let cmake = std::fs::read_to_string(repo.join("CMakeLists.txt")).map_err(|e| e.to_string())?;
    let get = |name: &str| -> Result<String, String> {
        cmake
            .lines()
            .find_map(|l| {
                l.trim()
                    .strip_prefix(&format!("set({name} "))
                    .map(|rest| rest.trim_end_matches(')').trim().to_string())
            })
            .ok_or_else(|| format!("{name} not found in CMakeLists.txt"))
    };
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .current_dir(repo)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();
    let version = format!(
        "{}.{}.0+{hash}",
        get("SLANG_VERSION_MAJOR")?,
        get("SLANG_VERSION_MINOR")?
    );
    std::fs::write(dest.join("VERSION"), format!("{version}\n")).map_err(|e| e.to_string())?;
    println!("vendored slang {version} into {}", dest.display());
    Ok(())
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (cmd, check) = match args.as_slice() {
        [c] => (c.as_str(), false),
        [c, flag] if flag == "--check" => (c.as_str(), true),
        _ => {
            eprintln!("usage: cargo xtask codegen [--check] | cargo xtask vendor");
            return ExitCode::from(2);
        }
    };
    match cmd {
        "codegen" => {}
        "vendor" => {
            return match vendor(&workspace_root()) {
                Ok(()) => ExitCode::SUCCESS,
                Err(e) => {
                    eprintln!("error: {e}");
                    ExitCode::FAILURE
                }
            };
        }
        _ => {
            eprintln!("unknown command `{cmd}`; expected `codegen` or `vendor`");
            return ExitCode::from(2);
        }
    }

    let root = workspace_root();
    let files = match generate(&root) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("error: {e}");
            return ExitCode::FAILURE;
        }
    };

    let mut stale = 0;
    for f in &files {
        let rel = f.path.strip_prefix(&root).unwrap_or(&f.path).display();
        if check {
            match std::fs::read_to_string(&f.path) {
                Ok(existing) if existing == f.contents => {}
                _ => {
                    eprintln!("stale: {rel}");
                    stale += 1;
                }
            }
        } else {
            if let Some(dir) = f.path.parent() {
                std::fs::create_dir_all(dir).expect("create generated dir");
            }
            std::fs::write(&f.path, &f.contents).expect("write generated file");
            println!("wrote {rel} ({} lines)", f.contents.lines().count());
        }
    }

    if check && stale > 0 {
        eprintln!(
            "{stale} generated file(s) out of date; run `cargo xtask codegen` and commit the result"
        );
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}
